### ISSUE TITLE
Refactor `preflight`

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1028]
## What

Refactor `preflight` considering #1015 and #1003. 

As a manager plugin
I want to know all the information that the host already has at preflight time
Because I can better prepare my backend system for eventual `register` calls
Because I can tailor my subsequent `resolve`-for-write responses more appropriately

As a host
I want to know early if a publish is likely to fail
Because then I can avoid expensive operations that are not supported

## Why

We cannot know what combination of workflows and host and manager capabilities are going to crop up.

A well-behaved host should give the manager as much information as it can at `preflight` time to have the best chance of the manager supporting intermediate `resolve`-for-write and the final `register` call.

That is, information that the host "owns" should be provided to the manager on `preflight` if it's available.

Information that the host needs in order to perform an operation should be `resolve`d with `kWrite` access from the entity returned by `preflight`.

Either of these cases may be true for a publish, depending on workflow.  

E.g. the host may know beforehand the MIME type of the file it is about to create, and so should communicate that to the manager; alternatively, the host may want to ask the manager what the MIME type of the file should be, so that it can choose an output codec before creating the file.  In either of these cases, retrieving the location to write the file to, via a subsequent `resolve` of the entity returned from `preflight`, will then have the required file extension information.

The same host operating on the same entity type could behave differently depending on the workflow.

## Acceptance Criteria

- `preflight` accepts a `TraitsData` hint per batch element, rather than a per-batch trait set
  * No checks are made to constrain the trait set across the supplied TraitsData
- A new `BatchElementError` type is added to indicate more information is needed in `preflight`
- Supporting documentation for publishing is updated to describe
   * That a host should always provide known data up front.
   * A manager can error if required preflight data is missing.

## Tasks

- [ ] Update BAL to new signature
- [ ] Update `apiComplianceSuite`
- [ ] Update `Manager`/`ManagerInterface`
- [ ] Update examples
- [ ] Add BatchElementError type `kInvalidPreflightHints`

## Examples

Given manager cannot resolve {property} with `kWrite`
When `resolve` is called with `kWrite` to retrieve {property}
Then trait property is unset

Given manager can resolve {property} with `kWrite` to {resolved}
When `resolve` is called with `kWrite` to retrieve {property}
Then trait property is {resolved}

Given manager requires {prelight_property} in `preflight`
When `preflight` is called without {preflight_property}
Then `BatchElementError` is returned with `kInvalidPreflightHint` error code

Given manager will resolve {property} with `kWrite` to {value} only if provided {prelight_property} in `preflight`
And `preflight` is called with {preflight_property}
When `resolve` is called with `kWrite` to retrieve {property}
Then trait property is {value}

Given manager will resolve {property} with `kWrite` to {value} if provided {prelight_property} in `preflight` or otherwise resolves to {other_value}
And `preflight` is called with {preflight_property}
When `resolve` is called with `kWrite` to retrieve {property}
Then trait property is {value}

Given manager will resolve {property} with `kWrite` to {value} if provided {prelight_property} in `preflight` or otherwise resolves to {other_value}
And `preflight` is called without {preflight_property}
When `resolve` is called with `kWrite` to retrieve {property}
Then trait property is {other_value}
