### ISSUE TITLE
[CI] Publish and use build artifacts for downstream testing

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1094]
## What

Publish pre-built artifacts for our supported platforms, both as part of release artifacts and PR artifacts.

## Why

This simplifies the CI of downstream projects, since they can use pre-built binaries rather than re-building themselves.

It also encourages experimentation, feedback and adoption by potential adopters.

## Acceptance Criteria

* Uploaded CMake install tree for CI runners: Ubuntu 20.04 (GCC 9), MacOS 11, Windows MSVC 2019.
* Every push, including merge to main.
* Artefact can be referred to by:
     - Git ref, e.g. `main`, `v1.0.0-beta.1.0`, `fe4653`
     - PR number
* Artefact name: `openassetio-<runs-on>`  (where `runs-on` matches GitHub runner)
* Solution for Python wheel filename construction from CI environment -> ABI suffix for `pip install`.
* Replace all custom rebuilds of OpenAssetIO in dependent projects.
* Easy to transplant CI config changes to other projects (so that when we find the need to use a tar.gz its easy).

### Tasks
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1181
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1201
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1410
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1408
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1409
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1235
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1182
