### ISSUE TITLE
Capability introspection API

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1113]
## What

Add a mechanism to introspect the capabilities of a manager (and later, perhaps a host).

## Why

#1101 defines that default implementations will throw a `NotImplementedError`, as such, we need a simple, cheap way to determine in advance whether a manager implements any specific capability to avoid onerous error handling boilerplate at method call sites.

We use the term 'capability' as this is not a method-wise concept. For example, `preflight` and `register` must both be implemented to support publishing. Similarly, the `getWithRelationsip*` methods must also be implemented together.

## Acceptance Criteria

- A host can trivially query the supported capabilities of a Manager.
- The method must be:
  - Invariant post `initialize`
  - Guaranteed cheap to call for the caller
  - Simple to use in conditionals without elaborate value unpacking
  - Customizable by the `ManagerInterface` implementation to support wrapper interfaces such as gRPC, fan-out or multiplex.
  - Easy as possible for a manager author to implement correctly/consistently.
- `apiComplianceSuite` validation that the manager honors its response from this method.
- If practical, default implementations/helpers provided that reduce programming error for the manager implementor.
- stringification name lookup table as per `Access`.
- Update `forManagers.dox`

```[tasklist]
### Tasks
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1119
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1128
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1124
- [ ] Create issues for update of dependent projects
```

## Notes

Sketch capturing preliminary discussions

```c++
namespace capability {

enum class ManagerCapability {
   kCustomState = 0  // createState, createChildState, persistenceTokenForState, stateFromPersistenceToken
   kCustomTerminology,  // updateTerminology
   // Put 'verbs' later to help group as we add methods like entityTraitSet etc
   kResolution,  // resolve
   kPublishing,  // preflight, register
   kRelationshipQueries,  // getWithRelationship*
   kDefaultEntityReferences,  // defaultEntityReference
}

static std::string managerCapabilityNames = { "resolution", ... };
} 

virtual bool ManagerInterface::hasCapability( ManagerCapability c ) const = 0;
```
Methods not covered above default to nops/empty data as they are effectively already introspection methods.

**Comment by foundrytom** [comment]
This is required before we can enact the ratified descision wrt default method implementations covered in #1101.

**Comment by foundrytom** [comment]
>     `kCustomState = 0  // createState, createChildState, persistenceTokenForState, stateFromPersistenceToken`
>    `kCustomTerminology,  // updateTerminology`

@feltech  @elliotcmorris  Would `kStateManagement` and `kTerminologyCustomization` be more in line with the others do you think?

**Comment by elliotcmorris** [comment]
Updated BAL : https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/pull/79
