### ISSUE TITLE
C++ Plugin System

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1115]
## What

Provide a C++ plugin system that mirrors the behaviour of the Python Plugin System (minus entry point loading).

## Why

For performance reasons, we need to support Manager Plugins being written in C++, and later, hybrid C++ and Python.

## Acceptance Criteria

- `CppPluginSystemManagerImplementationFactory` provided that mirrors the behaviour/interface of the [`PythonPluginSystemManagerImplementationFactory`](https://github.com/OpenAssetIO/OpenAssetIO/blob/main/src/openassetio-python/package/openassetio/pluginSystem/PythonPluginSystemManagerImplementationFactory.py), albeit without entry-point support.
- Use the existing environment variable `OPENASSETIO_PLUGIN_PATH`
- Plugin loading mechanism decoupled from the specifics of the manager factory so it can be used to provide other classes/plugins in the future (eg: UI delegates) (see the responsibility split in the Python plugin system).
- macOS, Windows and Linux support.
```[tasklist]
### Tasks
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1266
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1268
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1290
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1294
```

**Comment by feltech** [comment]
Moved https://github.com/OpenAssetIO/OpenAssetIO/issues/1293 and https://github.com/OpenAssetIO/OpenAssetIO/issues/1279 out of the epic. They will be tackled in subsequent milestones.
