### ISSUE TITLE
Host conveniences for callback methods

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1167]
## What

Add method overloads for the batch-first callback-based core API methods to provide more convenient signatures for common usage patterns.

This is part 2 of a 2 part epic. For part 1, which contains more design discussion, see #848.

## Why

The batch-first callback-based API was designed as the "lowest common denominator" signature that can be adapted for a large range of usage patterns (see [DR009](https://github.com/OpenAssetIO/OpenAssetIO/blob/main/doc/decisions/DR009-Batch-method-result-types.md)). It requires all calls to be provided a list of elements to query, and success and error callbacks that are called for each element, respectively.

However, for most usage patterns this is a clunky interface. For example, if you only have a single query, and you know/require  that it will succeed, then you may prefer a signature that takes a single element and returns a single response and any error is raised as an exception.

A huge advantage of the batch-first callback-based API is that such convenience signatures can be easily added as wrappers around this core signature, and exposed only on the host side. This allows the manager plugins to only write a single method, whilst hosts are given a selection of more convenient overloads to choose from.

As an aside: a future extension will be to move these convenience signature to the manager plugin, with a default implementation that the manager plugin can override if they choose. This would give manager plugins an opportunity to optimise the implementations of the convenience signatures for their particular backend.

## ACs

- In general, 4 additional signatures for each of the batch-first callback-based API methods, covering singular vs. batch inputs and exception throwing vs. result object error handling. By "result object" we mean
  - In Python either the success value, or a `BatchElementError` object.
  - In C++ a `std::variant` that contains either the success value or a `BatchElementError`.
- For batch-first but non-callback based methods, then only a singular convenience is required (i.e. `managementPolicy`).

### Tasks
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1239
- [x] #973
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1169
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1170
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1217
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/856

**Comment by feltech** [comment]
Closing as all sub-issues completed 🎉
