### ISSUE TITLE
V1.0.0 Docs Audit

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#1244]
## What
This issue is the landing issue for all the little "check the docs" "fix the docs" tasks that we'll need to do before 1.0

We should consider our overall audit strategy, because piecemeal "make the docs good" tickets come up too often and are often unachievable.

NOTE: Linked tickets below need refinement, very unlikely we address all or even the majority of them.

### Tasks

- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/478
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/470
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/758
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/786
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1179
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/855
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/927
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/946
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1055
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/82
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1160
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1184
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/106
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/351
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/774
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1043
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1258
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/550
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/745
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/235
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/124
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/801
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/846
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1315
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1223
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1398
- [ ] https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/issues/121
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1429
