### ISSUE TITLE
UI Delegation

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#1302]
## Why
UI delegation is essential to realise effective artist workflows based on manager driven behaviours.

### Tasks
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1367
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1380
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1403
