### ISSUE TITLE
Katana AssetAPI adapter

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1346]
## What

Shim plugin for Katana AssetAPI

## Why

Easier migration path and demoability.

### Tasks
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1375
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1376
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1377
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1424

**Comment by feltech** [comment]
The ownership of this issue is a bit awkward, since it really should be in the [KatanaOpenAssetIO](https://github.com/TheFoundryVisionmongers/KatanaOpenAssetIO) repo, now that it's available.  But tracking the issue cross-org (e.g. in the project view) wouldn't be possible 🤔

**Comment by feltech** [comment]
Now that the tasks are all complete, and KatanaOpenAssetIO has its own repo to track issues and progress, I think its finally safe to close this.
