### ISSUE TITLE
Improve support for more modern VFX Reference Platforms

### ISSUE THREAD

**Issue by feltech** [OpenAssetIO/OpenAssetIO#1351]
## What

Use a more recent VFX Reference Platform (2023+) as the default distribution target for OpenAssetIO, whilst making a best-effort to retain support for older (in-use) target platforms.

## Why

All our CMake, CI and PyPI defaults assume VFX Reference Platform 2022 is the predominant standard. The world has moved on and now the defaults make less sense to average consumers.

For example

* Forcing the deprecated `libstdc++` ABI on Linux means the default build is incorrect for anyone building OpenAssetIO for VFX CY23+.
* Our use of the [manylinux2014 container](https://github.com/pypa/manylinux?tab=readme-ov-file#manylinux2014-centos-7-based-glibc-217) for [cibuildwheel](https://github.com/pypa/cibuildwheel), which is CentOS 7 based, means that, by default, a `pip install openassetio` from PyPI is only compatible with C++ manager plugins built against the deprecated `libstdc++` ABI, i.e. is incompatible with VFX CY23+, even for Python 3.10+.

### Tasks
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1353
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1352
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/984
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/812
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1354
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1355
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1389

**Comment by feltech** [comment]
Closing as all sub-tasks are now done.
