### ISSUE TITLE
[Epic] `C++`/`Python` manager interop

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#191]
## What

As an integrator of OpenAssetIO into a host, or a developer of an OpenAssetIO manager plugin, I need to be able to freely split my implementation between one or both of `C++` or `Python` (based on CY2022 versions). 

I should not be tied into implementing any specific part of my code in one language or there other aside from for performance reasons to avoid issues such as the Python GIL.

## Why

The majority of "phase one" adoption targets (both managers and hosts) have code bases where critical business logics is only available in one of the two aforementioned languages. As OpenAssetIO is meant to be the "universal connector", the choice of host language should not dictate that of the manager, and vice versa.

In addition, there are many known hosts whose implementation is split between `C++` and `Python`, in such a fashion that developers leverage both languages to complete any specific feature work.

## Acceptance criteria

- As a host or manager developer, OpenAssetIO is available through both `C++` and `Python`.
  - A host written in either language should be able to interact with a manager written in the other, and vice versa.
  - A manager should be free to implement the `ManagerInterface` API in both languages at a method-wise granularity.
  - A `C++` to `C++` implementation should have absolute minimum intermediate code to support the highest possible performance path.
- Manager plugins written in any valid language should be loadable from `OPENASSETIO_PLUGIN_PATH`.
  - Dual language implementations supplied via discrete build targets can use the `identifier` to determine if they are part of the same logical plugin.  

### Tasks
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1115
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1324
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1340
- [x] https://github.com/OpenAssetIO/OpenAssetIO/issues/1202
- [x] https://github.com/OpenAssetIO/usdOpenAssetIOResolver/issues/40

**Comment by foundrytom** [comment]
It's worth keeping #201 in the back of the mind when working on this.

**Comment by feltech** [comment]
All subtasks complete 🎉  - closing.
