### ISSUE TITLE
Core `C`/`C++` Snagging List

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#319]
## What

This list covers topics to re-validate before moving further on with the core `C`/`C++` API:

 - [x] ~`SimpleString` naming~ done
 - [x] ~`SimpleMap` naming~ done
 - [x] ~`Should` traits be instances or static?~ Instance based traits provide solid value in terms of compile-time programmer error reduction, we can add in static versions for performance later.
 - [x] #343
 - [x] #340
 - [x] #335
 - [x] Rename `openassetio::specification::Specification` to `openassetio::Specification`
 - [x] Add default values for trait accessors, to allow `spec.someTrait().getSomeValue(defaultValue)` to return `None`
 - [x] ~Allow traits to define default values for un-set properties?~
 - [x] #348 
 - [x] ~Shared ptr for Specifications?~ Needed for the instance based Trait mechanism.
 - [x] ~C opaque handle definition style?~ Currently properly abstracted so we can deal with this later if needed.
