### ISSUE TITLE
[Epic] Build toolchain improvements

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#371]
## What

- [x] #376
- [x] #311*
- [x] #315*
- [x] #377
- [x] #392 
- [x] Document Changelog process
- [x] #577
- [ ] [Investigation] Version injection/other substitutions
- [ ] Conan recipe generation
- [x] Support cmake linter checks on all platforms
- [x] Decide the fate of `perftest`
- [x] CI disable failFast
- [x] ~Can we avoid the time sink of wheel building (takes 6s+ of py build)~
- [x] #484 

## Out of scope

- Publishing to public repositories
