### ISSUE TITLE
[Epic] Host API Improvements

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#813]
## What

Round off the roughest of edges for new Hosts using the API via Python or C++.

## Why

We hope to see host adoption rise this year, and there is currently missing C++ functionality and a general lack of quality-of-life conveniences that make implementing the API more arduous than it should be.

```[tasklist]
### Tasks
- [ ] OpenAssetIO/OpenAssetIO#815
- [ ] https://github.com/OpenAssetIO/OpenAssetIO-TraitGen/issues/11
- [ ] OpenAssetIO/OpenAssetIO#107
- [ ] OpenAssetIO/OpenAssetIO#798
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/822
- [ ] https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/issues/24
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1186
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1117
```
