### ISSUE TITLE
Paged getWithRelationship[s] API Design

### ISSUE THREAD

**Issue by elliotcmorris** [OpenAssetIO/OpenAssetIO#966]
Pager by value in the callback? -> EntityReferencePagerPtr
Add final Traitsdata arg thing

## Design Overview

Implements `GetRelationship[s]` using a Pager object, (cursor) approach.

Constructs `Pager` object as an outcome of a `Manager/ManagerInterface` function, following the same interface practices for the construction method (`getRelationship`), i.e, batch first, callback-based with singular conveniences, with a distinction made between expected errors dispatched to `BatchElementError` error callbacks, and exceptional errors handled via language exception (see [Error Handling](#error-handling))

As `Pagers` are distinctive in that they provide a second-order interface to the manager that can be called after the lifetime of the initial method has closed, there are some minor technical considerations to be made concerning argument mutability, (see [Copying Mutable References](#copying-mutable-references))

## Design Sketches

**The following are sketches, and should not be copied verbatim. Especially and including the documentation**

<details>
  <summary>ManagerInterface (Cpp)</summary>

```cpp
// Base Callback Formulation
using PagedGetRelationshipSuccessCallback = std::function<void(size_t index, EntityReferencePagerInterfacePtr)>;

/*
 * Construct a set of Pager objects capable of iterating in pages over
 * the entityReferences related to the input entityReference via the 
 * relationship traitSet.
 *
 * It is expected that the manager perform validation in this method.
 * You should initialize/assert the valid state of your backend,
 * throwing exceptions on errors.
 *
 * If the host provides you input that is malformed or in any
 * other way non-acceptable, you must call the error callback for the
 * specifically relevant Pager.
 *
 * Otherwise, for each input EntityReference, the provided success
 * callback should be called, provided with a constructed Pager object
 * ready to be iterated over.
 *
 * Each Pager should iterate over one of the entityReferences provided
 * as an argument, returning the entityReferences that are related to it
 * via the `releationship` argument.
 *
 * @throws std::exception. Any standard exception may be emitted from
 * this function to handle failure to initialize the backend.
 */

void ManagerInterface::getWithRelationship(
    const std::vector<EntityReference> &entityReferences,
    const TraitsDataPtr& relationship, const trait::TraitSet& resultTraitSet, size_t pageSize,
    const ContextConstPtr &context, const HostSessionPtr& hostSession,
    PagedGetRelationshipSuccessCallback successCb,
    BatchElementErrorCallback failureCb,);

/*
...
 * Otherwise, for each input EntityReference, the provided success
 * callback should be called, provided with a constructed Pager object
 * ready to be iterated over.
 *
 * Each Pager should iterate over one of the relationships provided as
 * the relationship argument. Ie, for a relationship [Child, Version], a
 * pager should be constructed to return all the entityReferences related
 * by `Child`, and then a second pager should be constructed to return
 * all the entityReferences related by `Version`.
 */
 ...
void ManagerInterface::getWithRelationships(
    const EntityReference& entityReference,
    const TraitsDataPtrs& relationships, const trait::TraitSet& resultTraitSet, size_t pageSize,
    const ContextConstPtr &context, const HostSessionPtr& hostSession,
    PagedGetRelationshipSuccessCallback successCb,
    BatchElementErrorCallback failureCb,);
```

</details>

<details>
  <summary>Manager::getWithRelationship (Cpp)</summary>

```cpp
// Base Callback Formulation
// The index in the case of `getWithRelationship` is the index of the input entityReference.
using PagedGetRelationshipSuccessCallback = std::function<void(size_t index, EntityReferencePagerPtr)>;

/*
 * Construct a set of Pager objects capable of iterating in pages over
 * the entityReferences related to the input entityReferences via the 
 * relationship traitSet.
 *
 * It is expected that the manager perform validation in this method.
 * The host can expect, if the input provided is malformed or in any
 * other way non-acceptable to the manager, to receive an error callback.
 * Otherwise, for each input EntityReference, the manager will receive
 * a constructed Pager object in the success callback.
 *
 * This method may be expected to perform a network query to perform
 * validation, do not assume a quick return.
 *
 * @throws std::exception. Any standard exception may be emitted from
 * this function to handle failure to initialize the backend.
 */
void Manager::getWithRelationship(
    const EntityReferences &entityReferences,
    const TraitsDataPtr& relationship, size_t pageSize,
    const ContextConstPtr &context, const HostSessionPtr& hostSession,
    PagedGetRelationshipSuccessCallback successCb,
    BatchElementErrorCallback failureCb,
    const trait::TraitSet& resultTraitSet = {});

/*
 * Singular Variant Convenience
 * Uses the batch version as its underlying implementation
 */
std::variant<EntityReferencePagerPtr, BatchElementError> getWithRelationship(
   const EntityReference &entityReference,
   const TraitsDataPtr& relationship, size_t pageSize,
   const ContextConstPtr &context, const HostSessionPtr& hostSession,
   const trait::TraitSet& resultTraitSet = {});

/*
 * Singular Exceptional Convenience
* Uses the batch version as its underlying implementation
 */
EntityReferencePagerPtr getWithRelationship(
   const EntityReference &entityReference,
   const TraitsDataPtr& relationship, size_t pageSize
   const ContextConstPtr &context, const HostSessionPtr& hostSession,
   const trait::TraitSet& resultTraitSet = {});
  
/*
 * Multi Variant Convenience
 * Uses the batch version as its underlying implementation
 */
std::vector<std::variant<EntityReferencePagerPtr, BatchElementError>> getWithRelationship(
   const EntityReferences &entityReferences,
   const TraitsDataPtr& relationship, size_t pageSize
   const ContextConstPtr &context, const HostSessionPtr& hostSession,
   const trait::TraitSet& resultTraitSet = {});

/*
 * Multi Exceptional Convenience
* Uses the batch version as its underlying implementation
 */
std::vector<EntityReferencePagerPtr> getWithRelationship(
   const EntityReferences &entityReferences,
   const TraitsDataPtr& relationship, size_t pageSize
   const ContextConstPtr &context, const HostSessionPtr& hostSession,
   const trait::TraitSet& resultTraitSet = {});
```

</details>

<details>
  <summary>Manager::getWithRelationships (Cpp)</summary>

```cpp
// Base Callback Formulation
// The index in the case of `getWithRelationships` is the index of the input relationship.
using PagedGetRelationshipSuccessCallback = std::function<void(size_t index, EntityReferencePagerPtr)>;

/*
 * Construct a set of Pager objects capable of iterating in pages over
 * the entityReferences related to the input entityReference via the 
 * relationship traitSet.
 *
 * It is expected that the manager perform validation in this method.
 * The host can expect, if the input provided is malformed or in any
 * other way non-acceptable to the manager, to receive an error callback.
 * Otherwise, for each input EntityReference, the manager will receive
 * a constructed Pager object in the success callback.
 *
 * This method may be expected to perform a network query to perform
 * validation, do not assume a quick return.
 *
 * @throws std::exception. Any standard exception may be emitted from
 * this function to handle failure to initialize the backend.
 */
void Manager::getWithRelationships(
    const EntityReference &entityReference,
    const TraitsDataPtrs& relationships, size_t pageSize,
    const ContextConstPtr &context, const HostSessionPtr& hostSession,
    PagedGetRelationshipSuccessCallback successCb,
    BatchElementErrorCallback failureCb,
    const trait::TraitSet& resultTraitSet = {});

/*
 * No singular conveniences are provided for `getWithRelationships` as they
 * are identical to `getWithRelationship`.
 */
 
/*
 * Multi Variant Convenience
 * Uses the batch version as its underlying implementation
 */
std::vector<std::variant<EntityReferencePagerPtr, BatchElementError>> getWithRelationships(
   const EntityReference &entityReference,
   const TraitsDataPtrs& relationships, size_t pageSize
   const ContextConstPtr &context, const HostSessionPtr& hostSession,
   const trait::TraitSet& resultTraitSet = {});

/*
 * Multi Exceptional Convenience
* Uses the batch version as its underlying implementation
 */
std::vector<EntityReferencePagerPtr> getWithRelationship(
   const EntityReference &entityReference,
   const TraitsDataPtrs& relationships, size_t pageSize
   const ContextConstPtr &context, const HostSessionPtr& hostSession,
   const trait::TraitSet& resultTraitSet = {});
```

</details>

<details>
  <summary>EntityReferencePagerInterface (Cpp)</summary>

```cpp
/*
 * EntityReferencePagerInterface, implemented by the manager.
 * Deals with the retrieval of paginated data from the backend at the
 * behest of the host.
 *
 * To support as wide array of possible backends as possible,
 * OpenAssetIO places no restraints on the behaviour of this type
 * concerning performance, however, it is considered friendly to
 * document the performance characteristics of your Pager implementation.
 */
class EntityReferencePagerInterface {
 public:
    using Page = std::vector<EntityReference>;

    // Explicitly disallow copying.
    EntityReferencePagerInterface(const& EntityReferencePagerInterface) = delete;
    EntityReferencePagerInterface& operator=(const EntityReferencePagerInterface&) = delete;
    // Allow moving.
    EntityReferencePagerInterface(EntityReferencePagerInterface&&) noexcept = default;
    EntityReferencePagerInterface& operator=(EntityReferencePagerInterface&&) noexcept = default;

    /* Manager should override destructor to be notified when query has
     * finished.
     */
    virtual ~EntityReferencePagerInterface() = default;

    /*
     * Whether or not there is more data accessible by advancing the
     * page. The mechanism to acquire this information is variable, and
     * left up to the specifics of the backend implementation.
     */
    virtual bool hasNext(const HostSessionPtr&) = 0;

    /*
     * get and next are separated to allow traversal through a list
     * without necessarily fetching the all the data.
     *
     * Whilst it is not a set rule that `next` must be a cheap operation
     * as some backends cannot support this, it is considered friendly
     * for `next` to be a cheap call that allows traversal, whilst `get`
     * performs the actual work.
     * Documenting the performance characteristics of these methods is
     * highly encouraged.
     */
    virtual Page get(const HostSessionPtr&) = 0;
    virtual void next(const HostSessionPtr&) = 0;
};
```

</details>

<details>
  <summary>EntityReferencePager (Cpp)</summary>

```cpp
/*
 * The OpenAssetIO EntityReferencePagerInterface wrapper object. Following a similar
 * pattern to Manager and ManagerInterface
 *
 * This is the object the host interacts with, allowing for addition
 * of convenience functions, as well as the insertion of middle-layer
 * functionally, (such as the imminent arrival of an auditing system.)
 *
 * Due to the variance of backends, construction, `hasNext`, `get` and
 * `next` may all reasonably need to perform non trivial, networked
 * operations, and thus performance should not be assumed.
 */
class EntityReferencePager {
 public:
    using Page = EntityReferencePagerInterface::Page;

    /*
     * EntityReferencePager cannot be copied, as each object represents a single
     * paginated Query.
     * Destruction of this object is tantamount to closing the query.
     */
    EntityReferencePager(EntityReferencePagerInterface::Ptr EntityReferencePagerInterface, const HostSessionPtr&);
    EntityReferencePager(const EntityReferencePager&) = delete;
    EntityReferencePager& operator=(const EntityReferencePager&) = delete;
    EntityReferencePager(EntityReferencePager&&) noexcept = default;
    EntityReferencePager& operator=(EntityReferencePager&&) noexcept = default;
    ~Pager() = default;

    /*
     * Whether or not there is more data accessible by advancing the
     * page. This method may be slow depending on backend implementation.
     */
    bool hasNext();

    /*
     * get and next are separated to allow traversal through a list
     * without necessarily fetching the all the data.
     * Neither of these methods however, are guaranteed to be cheap,
     * as some backends have no choice but to retrieve the data when
     * they advance the page.
     */
    Page get();
    void next();


 private:
    EntityReferencePagerInterface::Ptr entityReferencePagerInterface_;
    HostSesstionPtr hostSession_;
};
```

</details>

## Implementation Notes
</details>

<details>
  <summary>Error Handling</summary>
 
Error handling will follow the same style as previous methods in `Manager`, yielding to an error callback with an `index` and a `BatchElementError` (see note) to handle any errors in the input data, whilst errors in the backend (ie, non-expected, the backend isn't working sort of errors,) will be thrown as exceptions. See #961 

> **Note**
>
> Speccing out this work made the inappropriateness of `BatchElementError` as a name for this error type more clear. As really it's more of a `InputArgumentsAreWrongSomehowError`. This is already showing a bit of dissonance for the singular, non-batch conveniences. > We plan to rename this at some point.

This error handling philosophy applies to `getRelationships`, however, an important concept to note is that once the `Pager` has been constructed, non-exceptional errors are no longer expected. This is why the pager maintains a more convenient return-based interface, and does not have capability to communicate via error-types.
</details>

<details>
  <summary>Copying Mutable References</summary>

Due to `Pagers` having a lifetime that exists beyond the method call that provides the initial arguments, we are presented a consideration
concerning arguments passed by pointer (which, thanks to our python integrations, is almost everything.)

It would be a poor behaving manager that changed the data pointed to in these arguments, as it would effect parts of the system outside its scope.

Two choices present immediately :
  - Document that the manager **must not** mutate the data in these pointers, and that if they wish to work with it, they should themselves copy it.
  - Use the `Manager/ManagerInterface` dependency inversion to only pass copied objects to `ManagerInterface::entityVersions`, thus removing the ability for managers to create problems. (The copy mechanism may vary, a prime example being that `Context` likely wants to call `createChildContext` and use that.)

**We have chosen to simply document that the data must not be mutated.**
The difference between the Pager and regular methods is that the Pager may store these items long term. Of these items :
- `vector<EntityReferences>` : These are value types anyway
- relationship : TraitsDataPtr : This may be held and may be mutated. However we do not feel like a manager is likely to hold onto this arg beyond the initial construction of the query.
- context : This is passed a a const pointer, and also unlikely manager will hold onto this past initial query. (the locale may still be edited! But this risk is consistent with other uses of context as an argument across the api.)
- hostSession : Hostsession is expected to change. Plus there's no need to be storing it since we pass it with every method call.

Of these args, relationship, and context to a lesser extent due to const ptr, are the only ones where the reasoning changes vs normal methods due to being a long-lived pager object.
We feel that documentation is sufficient, and copying these objects would be an undue pessimisation for only a small risk.

</details>

<details>
  <summary>Performance Philosophy</summary>

To enable the widest variety of backends, we have not placed hard performance limitations on either the method to construct a `Pager`, nor the members of the `Pager` itself.

However, it is unlikely any manager backends will need to be potentially unperformant in `all` of these cases. We should to put a strong focus in the documentation communicating the potential slow-performance of these methods to the host, whilst also communicating the the manager what a friendly manager would do (particularly concerning `next` and  `get`), and also encouraging the manager to document their performance characteristics well.
</details>

<details>
  <summary>The Last Page</summary>

When `hasNext` is false, the behaviour of the methods is defined thusly :
- `next` advances the pager to an invalid state, representing "beyond the last page". It does not error.
- `get`, in the case where the pager is in a "beyond the last page" state, returns an empty container.
- ` hasNext` continues to return false. 
  
</details>

## Implementation Strategy

```[tasklist]
### Tasks
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/971
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/972
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/974
- [ ] https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/issues/46
```

**Comment by foundrytom** [comment]
`hasMore` -> `hasNext`
