### ISSUE TITLE
Migrate Versions API to MediaCreation

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#979]
## What

[DR017](https://github.com/OpenAssetIO/OpenAssetIO/pull/962) decided that the versions API will be removed from the core API and migrated to MC. Remove the existing API methods.

## ACs

- There are no versioning related methods in the core API
- Terse documentation redirects users to their vertical-specific traits library

## Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/issues/48
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/980
- [ ] https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/issues/49
```
