### ISSUE TITLE
Migrate `exceptions.py` to C++

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#997]
## What

Determine the C++ equivalent to the error hierarchy in `exceptions.py`

## Why

Python custom exceptions need to be removed as they bifurcate error handling.

## ACs

- `exceptions.py` removed
- Developers are steered into providing user-meaningful info when throwing errors.
- Issues raised to cover breaks and/or upstream projects updated.
- Issues for best practice changes in upstream projects logged.

## Notes

- Some are YAGNI eg `UserCancelled`,`RetryableError`
- Some come from the pre-batch days and are now served by a `BatchElementError`
- We need suitable hierarchy of exceptions that ensure entity-related exceptions carry user-meaningful information (eg the base entity error in py). And also to simplify catching at higher levels of other partitioning of the error space.
- Stick with current approach for instantiating Python exceptions from C++
- Out of scope: Other exceptions thrown out of explicit "openassetio logic" in manager/host code, improved converstion of pytbind->c++->pybind.
```[tasklist]
### Tasks
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1070
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1071
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1073
- [ ] https://github.com/OpenAssetIO/OpenAssetIO/issues/1083
- [ ] https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/issues/74
- [x] Check which upstream projects need to migrate to new exception hierarchy
- [x] Re-enable disabled integration tests
- [x] Discuss strategy for inappropriate BatchElementError given to error callback
```
